version: '3'

tasks:
  build:
    desc: Build the app
    cmds:
      - go build -o bin/api cmd/api/main.go
  
  run:
    desc: Run the app
    cmds:
      - go run cmd/api/main.go

  docker-up:
    desc: Start the database container
    cmds:
      - docker-compose up -d

  docker-down:
    desc: Stop the database
    cmds:
      - docker-compose down

  lint:
    desc: Run lints
    cmds:
      - golangci-lint run